### PR TITLE
Extend run to accept QueryConfig

### PR DESCRIPTION
**Pull request by adamochayon**
#83

### CODE REVIEW

**Comment by adelsz** [comment]
Thanks @adamochayon!
I think it is better to keep the `IDatabaseConnection` connection interface as generic as possible. Instead of locking it to `IQueryConfig` it would be better to add an optional argument there:
```diff
interface IDatabaseConnection {
-  query: (query: string, bindings: any[]) => Promise<{ rows: any[] }>;
+  query: (query: string, bindings: any[], options?: any) => Promise<{ rows: any[] }>;
}
```
We can then extend the `PreparedQuery.run` method to forward an additional `options` parameter.

One can then create an adaptor connection:
```ts
const nodePgConnection: IDatabaseConnection = {
  query: (query: string, bindings: any[], options?: IQueryConfig) => connection({
    ...options, text: processedQuery, values: bindings
  })
}; 

// Used like this:
sampleQuery.run({ userId: 123 }, nodePgConnection, { name: 'prepared-query' });
anotherQuery.run({ userId: 123 }, nodePgConnection);
```

**Comment by adamochayon** [comment]
I see what you're saying - That sounds like a good idea :)

**Comment by adelsz** [comment]
Do you want to take a stab at it as part of this PR?

**Comment by adamochayon** [comment]
@adelsz I think you have a clearer vision on how you would want it to look.
Feel free to use this PR as a starting point if you would like :)

**Pull request closed without merging**
