### PR TITLE
chore(dynamic-queries): added casting for `IS NULL` section of Dynamic Queries & replace `yarn` in `README` with `npm`

### PR DESCRIPTION
**Pull request by GervinFung**
Hi, I accidentally closed my previous PR while I was trying to update the branch, so I created one again. Unlike previous PR, this time there were only 2 changes.
1. README - where I change `yarn` keyword to `npm`, since `package-lock.json` is used
2. Docs - added casting for Dynamic Queries to improve clarity

Below are the differences in the docs generated. Look forward to your reply and perhaps the merge of my PR to main branch. Thank you

|Before|After|
|:---|:---|
|before| after|

### CODE REVIEW

**Comment by adelsz** [comment]
Thanks @GervinFung!
Just to confirm, are you saying that that query in the docs doesn't work as is?

**Comment by GervinFung** [comment]
> Thanks @GervinFung! Just to confirm, are you saying that that query in the docs doesn't work as is?

Thank you for your reply, for nullable the query only work if I cast it, for example
```sql
WHERE (:name :: TEXT IS NULL OR name = :name)
```
If I don't cast it, it will throw `could not determine data type of parameter` error, so I need to cast it once before `IS NULL`

FYI, I am using the latest stable version - `0.13.0`

**Review by adelsz — APPROVED** [review]
Thanks for the clarification @GervinFung. Merging.

**Comment by GervinFung** [comment]
> Thanks for the clarification @GervinFung. Merging.

You are welcome, thank you for creating such a wonderful tool, keep it up 👍

**Pull request merged**
