### PR TITLE
feat(tag): expose operation name

### LINKED ISSUE #346: feat: allow operation name to be logged/tracked
## Problem
Currently, it is not easy to locate which file is responsible for which query during runtime (especially development), because only `query` and `bindings` are exposed to clients:
```ts
  export interface IDatabaseConnection {                                                                        
      query: (query: string, bindings: any[]) => Promise<{
          rows: any[];
      }>;
  }  
```

## Suggestion
Add an optional third parameter to `query`, named `meta`, which can include information such as the query name etc.

### PR DESCRIPTION
**Pull request by wongjiahau**
Closes #346

### CODE REVIEW

**Comment by m-ronchi** [comment]
warning: the new signature will not be compatible with `pg` / `pg-pool` (their third parameter, if present, must be a callback function)

**Comment by JesseVelden** [comment]
I'm also actually wondering what kind of Postgres client you're using.

**Comment by wongjiahau** [comment]
@JesseVelden I'm using `pg`.

**Comment by wongjiahau** [comment]
@m-ronchi you just need to add a wrapper around whatever client you are using

**Comment by m-ronchi** [comment]
I am using official `pg` too, and I get runtime errors with both `pg.Pool()` and `pg.Client()`: 

```ts
interface IDatabaseConnection {
      query: (
        query: string,
        bindings: any[],
        meta: {
          /** Name of this query. For example: `"findBookById"` */
          name: string;
        },
      ) => Promise<{ rows: any[] }>;
    }
    // const pool = new Pool({ connectionString: "postgres://..." });
    const db = new Client({ connectionString: "postgres://..." });
    await db.connect();
    const c: IDatabaseConnection = db; // or pool, or await pool.connect(), result is the same
    const r = await c.query("SELECT 1 + 1 as s", [2], { name: "test" });
```

```
TypeError: this.callback is not a function
    at Query.handleError (/.../offers-api/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/.../offers-api/node_modules/pg/lib/client.js:335:17)
    at Connection.emit (node:events:520:28)
    at Connection.emit (node:domain:475:12)
    at /.../offers-api/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/.../offers-api/node_modules/pg-protocol/src/parser.ts:104:9)
    at Socket.<anonymous> (/.../offers-api/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

this is a breaking change, and it breaks at runtime instead of compile time too.

**Comment by adelsz** [comment]
Thanks for the PR @wongjiahau. Unfortunately, breaking compatibility with `pg` is a major problem, so can't really merge it as is. We might return to this once/if we decide to refactor the TaggedQuery class.

**Comment by wongjiahau** [comment]
No worries, thanks for your work too!

**Pull request closed without merging**
