### PR TITLE
Allow to specify param nullability via !

### LINKED ISSUE #242: [feature request] insert/update params type nullability
currently, input types for insert and update queries (the ones in `SET column_name = :param`) are always defined as `param: Type | null | void`.

ideally, pgtyped should infer nullability. but you said in #118 that can't be done easily.

you could implement a new syntax for explicitly specifying nullability and generate nullable types accordingly, e.g:
- `:param` -> current behaviour (no breaking changes), emit warning if ambiguous (possibly behind a flag)
- `:?param` or `:param?` -> force nullable type
- `:!param` or `:param!` -> force non nullable type

also, when you generate properties as `name: Type | null | void`, parameters are required by TS (have to explicitly set the to undefined), it would be better to generate them as `name?: Type | null` (`undefined` is still accepted by TS, but you can also omit that property).

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Fixes #242 

I'm not sure if I handled the snapshots of the tests correctly, basically just updated them, not sure if there is more to it. If you want some more specific tests or anything changed, feel free to get back to me :)

### Scalar

```sql
/* @name GetAllComments */
SELECT * FROM book_comments WHERE id = :id! OR user_id = :id;
```

Since `:id` is required at least once, it will **not** be nullable:

```
export interface IGetAllCommentsParams {
  id: number;
}
```

### Array

```sql
/*
  @name GetAllCommentsByIds
  @param ids -> (...)
*/
SELECT * FROM book_comments WHERE id in :ids!;
```

We can also handle array spread syntax in the query itself

```
export interface IGetAllCommentsByIdsParams {
  ids: readonly (number)[];
}
```

### Pick 

```sql
/*
  @name InsertSingleComment
  @param comment -> (userId!, commentBody)
*/
INSERT INTO book_comments (user_id, body) VALUES :comment;
```

In the pick syntax we have to declare required keys in the param declaration, since the object itself is required anyway

```
export interface IInsertSingleCommentParams {
  comment: {
    userId: number,
    commentBody: string | null | void
  };
}
```

### Array Pick 

```sql
/*
  @name InsertBooks
  @param books -> ((rank!, name!, authorId)...)
*/
INSERT INTO books (rank, name, author_id)
VALUES :books RETURNING id as book_id;
```

In the pick syntax we have to declare required keys in the param declaration, since the array itself is required anyway
```
export interface IInsertBooksParams {
  books: readonly ({
    rank: number,
    name: string,
    authorId: number | null | void
  })[];
}
```

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Totally forgot about the docs, will try to write sth up within this week!

**Comment by jgonera** [comment]
#242 also suggested replacing `name: Type | null | void` with `name?: Type | null`. Is that something you'd also be open to @adelsz?

**Comment by adelsz** [comment]
Thanks for the PR @JohnnyCrazy! Merging as is, docs can be added later.

**Comment by isaac-leonard-uni** [comment]
When will this reach npm and does it work with non object substitutions?

**Comment by fmmoret** [comment]
@adelsz is the npm publish blocked on docs?

@JohnnyCrazy do you have a branch w/ docs on it already?

I would love this change, and I could make the couple doc changes if that's all that's blocking.

**Pull request merged**
