### PR TITLE
feat: support enum array types

### PR DESCRIPTION
**Pull request by maylukas**
Fetching type info for element types and mapping enum arrays

Solves: #218

### CODE REVIEW

**Comment by adelsz** [comment]
Thank you for this PR @maylukas . Can you please rebase it on latest master?

**Comment by maylukas** [comment]
@adelsz I rebased on master. I had some issues with failing tests due to improper prettier formatting. I reformatted with prettier and placed prettier-ignores where applicable.

Also I noticed, that the type generation did not work as nothing changed when query files were changed. Before rebasing, this worked. Maybe this has also something to do with my local setup (I haven't worked with lerna much).

**Comment by adelsz** [comment]
@maylukas Looks like there still remain some prettier issues. I tried fixing them myself but this PR [doesn't allow pushes from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by maylukas** [comment]
@adelsz Unfortunately this option was not available. Maybe because the repository was created in a group?
I granted you access to the repository directly though.

I just checked again and rebased onto main but when I run the tests locally, these prettier issues don't show for some reason

**Review by adelsz — APPROVED** [review]
Interesting. Either way, thanks for granting me push access, I have updated the PR with `yarn lint --fix` and it should be good to merge now. Thanks again @maylukas, good work!

**Comment by maylukas** [comment]
@adelsz Thanks for your help!

Do you have any timeline for when you are planning the next release of this library?

**Comment by adelsz** [comment]
@maylukas Released in v0.13.0 😄

**Pull request merged**
