### PR TITLE
feat: add support for streaming

### PR DESCRIPTION
**Pull request by EloB**
Link to my [feature request issue](https://github.com/adelsz/pgtyped/issues/568)!

## More context:
`pg-cursor` is maintained by the same author as `pg` and also part of his official documentation.

### Links:
- **`pg-cursor` is documented on `README`**
 https://github.com/brianc/node-postgres

- **`pg-cursor` is located in same monorepo as `pg`**
 https://github.com/brianc/node-postgres/tree/master/packages/pg-cursor

- **Official `pg-cursor` documentation**
 https://node-postgres.com/apis/cursor

## Usage
```ts
import ( IDatabaseConnection } from "@pgtyped/runtime/lib/tag";
import { Client } from "pg";
import Cursor from "pg-cursor";

const client = new Client({ /* ... */ });
const connection: IDatabaseConnection = {
  query: (query, bindings) => client.query(query, bindings),
  stream: (query, bindings) => client.query(new Cursor(query, bindings)),
};

const getBigData = sql`SELECT * FROM big_data`;
const cursor = getBigData.stream({}, connection);
let rows = await cursor.read(1000);
while (rows.length) {
  // Do something with the fetched rows...
  
  // Then fetch another 1000 rows.
  rows = await cursor.read(1000);
}
```

Fixes https://github.com/adelsz/pgtyped/issues/568

### CODE REVIEW

**Review by adelsz — APPROVED** [review]
Thanks @EloB. Looks really good.
Will you be able to add a change to docs to document this?

**Comment by EloB** [comment]
Maybe when I have time. Would appreciate if this got merged. Right now I patched it for my client using `pnpm patch`. I'll end my contract this friday. Maybe after I can add it.

**Comment by adelsz** [comment]
Thanks @EloB

**Comment by ungeordnet** [comment]
@adelsz when will you release this?

**Pull request merged**
