### PR TITLE
Prettier: fixed configuration and ran agains the current state of the repo

### PR DESCRIPTION
**Pull request by golergka**
I'm not sure if the prettierrc in the root of the project was in the correct state — may be I should've updated options before running it?

### CODE REVIEW

**Comment by golergka** [comment]
I would also implement husky pre-commit hooks that would automatically run prettier as well as lint fix formatters, if you don't mind.

**Comment by adelsz** [comment]
Thanks @golergka, it is nice how all the markdowns, yaml and json look now. 
Seems like there was a typo in `arrowParens`, I would actually suggest to remove that setting to avoid removing parenthesis from existing code.
My IDE reformats all files using prettier by default, but only on TS files. I don't think enforcing it with a husky hook makes sense as it is already enforced at CI level.

**Comment by golergka** [comment]
Removed the option as per your request, but it's still a lot of modifications to existing code, may be I should tweak the config further so it won't change as much?

Also, the way prettier wraps the `sql<ISomeLongNameQuery> = ...` strings looks a bit weird, I created an issue about it: https://github.com/prettier/prettier/issues/9196

**Comment by adelsz** [comment]
Thanks,
It looks like most of the remaining TS changes are in files generated by pgTyped (in `pkg/example`) or ANTLR (in `packages/query/src/loader/*/parser/`).
I think we should add a rule to ignore these files in prettier because we have no control over their format. Otherwise I think the PR looks great and can't wait to merge it.

**Comment by golergka** [comment]
I've added these files to be ignored by prettier and tslint. This PR should probably be squashed on merge, so the reversed changes don't screw up these files history.

**Pull request merged**
