### PR TITLE
Generation parallelisation

### PR DESCRIPTION
**Pull request by golergka**
Implemented parallel processing using jest-workers package. The console output is not yet ideal (it should probably display the current state of different workers as jest does), but I've tested it on our project, and it significantly reduced generation times.

### CODE REVIEW

**Comment by adelsz** [comment]
Looks good!
Never heard of `jest-workers` but really like how it promisifies the worker pool. I will try to test it out this week.
Do you plan on improving this PR further, maybe tweaking the stdout options?
Otherwise I will be happy to review/merge as is.

**Comment by golergka** [comment]
I'm still not sure that jest-workers is a package that is really intended to be used outside of jest; I just thought that jest is an example of package that is doing somethjng very similar and decided to copy their approach.

As for tweaking output options, I want to get to it, but I'm not sure if I'll be able to do it before the next weekend, so I'd rather do it as a separate PR a bit later.

**Comment by golergka** [comment]
@adelsz sorry about leaving this PR hanging, completely slipped my mind. Looks good now, would you mind taking a look? I'd like to improve on the stdout, but I probably will get to it much later, and in a separate PR

**Comment by adelsz** [comment]
Thanks @golergka,
I have just noticed that parsing errors are no longer propagated to the CLI after your changes.
Here is an example error message that becomes silently ignored when using this PRs version:
Screenshot 2020-12-19 at 14 54 41

This is the only remaining blocker for merging this.

**Comment by golergka** [comment]
> Hey everyone, would love to see this cleaned up and merged. Generation is taking >60 seconds on my project. Is there anything I can do to push this through the finish-line?

I think you can address the issues @adelsz highlighted earlier — you'd have to figure out how to properly channel output of parallel workers back into the main thread to output all the errors correctly.

**Comment by golergka** [comment]
> @golergka I just pulled in the source code and inspected it to see if I could clean it up and I'm actually curious why we need to have a queue at all.
> 
> 
> 
> It seems that the `processQueue` should be able to [run several promises in-parallel here](https://github.com/adelsz/pgtyped/blob/c44be17cabb31ecc7c7800f0148645cf555222e0/packages/cli/src/index.ts#L102) and skip adding a whole new dependency altogether?

I'm sorry, but its been over a year after I worked on this, and I currently don't have resources to go back and invest any real time into singing this question.

However, as far as I remember, the point here was not in just running async promises simultaneously in the same process, but to actually create several processes.

**Comment by adelsz** [comment]
Alright, so I managed to bring this up to date and fix the output issues by piping the workers streams into the main one https://github.com/adelsz/pgtyped/pull/186/commits/50d37b7a993a5108ba52851660d463a92a1d89eb

**Comment by maxpain** [comment]
I still have performance problems with large .sql files with ~100 queries.

**Pull request merged**
