### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by bradleyayers**
Removes some dead code that isn't used (in the spirit of trying to improve on-boarding to the code base).

### CODE REVIEW

**Review by adelsz — CHANGES_REQUESTED** [review]
Looks good overall. The files at `packages/query/src/loader/sql/parser/` are dynamically generated, so lets ignore them to prevent diffs on the next generator run.

**Comment by bradleyayers** [comment]
> Looks good overall. The files at `packages/query/src/loader/sql/parser/` are dynamically generated, so lets ignore them to prevent diffs on the next generator run.

Yes there's an annoying trade-off to pick here because `noUnusedLocals` can't be set on a per-file basis, so the options I can see the pick between are:

1. Turn off `noUnusedLocals` (with it on, tsc will error on those files).
2. Leave `noUnusedLocals` on, and manually update the generated files (I went with this option because I figured regenerating the parser is going to be less frequently done than editing other files).
3. Fix antlr4ts (https://github.com/tunnelvisionlabs/antlr4ts/issues/412) to not emit files with unused imports.
4. Use TypeScript project references and introduce a new project for generated files from antlr4ts, and in that project's tsconfig.json turn off `noUnusedLocals`.
5. Run another command after antlr4ts that modifies the generated files, but I have no good ideas on how that modification would work.

Perhaps a good compromise is to just turn off the `noUnusedLocals`, it's a bit unfortunate but the other changes are still valuable IMO.

**Comment by adelsz** [comment]
Got it. How about enforcing this [tslint](https://palantir.github.io/tslint/rules/no-unused-variable/) rule instead of the tsc setting?
Current tslint [config](https://github.com/adelsz/pgtyped/blob/master/tslint.json) already correctly ignores the generated files.

**Comment by bradleyayers** [comment]
Yep that looks good, I'll have a look at that option.

**Pull request merged**
